### ISSUE TITLE
Little bug in startup

### ISSUE THREAD

**Issue by BozeBro** [StaticMania/blogge-hugo-theme#4]
When I initially tried the setup tools, I believe there were some bugs but I might have run some things incorrectly. 
git submodule add git@github.com:StaticMania/blogge-hugo.git themes/coHubloggeb should instead be 
git submodule add git@github.com:StaticMania/blogge-hugo.git themes/blogge

and then the theme in config.toml should be blogge instead.

**Comment by shinyzhu** [comment]
Now you should use:

```
git submodule add https://github.com/StaticMania/blogge-hugo-theme themes/blogge-hugo-theme
```

And then update your `config.toml`:

```
theme = 'blogge-hugo-theme'
```
